"use client";

import type { AnalysisResult, Incident } from "@blackbox/schemas";
import { CATEGORY_LABELS } from "@/lib/format";

export function SummaryCard({
  incident,
  analysis,
}: {
  incident: Incident;
  analysis: AnalysisResult | null;
}) {
  return (
    <div className="rounded-lg border border-edge bg-surface-1">
      <header className="border-b border-edge px-4 py-2.5">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-ink-dim">
          Incident summary
        </h2>
      </header>
      <div className="space-y-4 p-4 text-sm leading-relaxed">
        <div>
          <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-ink-faint">
            What happened
          </h3>
          <p>{incident.summary}</p>
        </div>
        {analysis && (
          <>
            <div>
              <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-ink-faint">
                Why BlackBox believes it happened
              </h3>
              <p>
                <span className="font-medium text-accent">
                  {CATEGORY_LABELS[analysis.failure_category]}
                </span>{" "}
                — {analysis.explanation}
              </p>
              <p className="mt-1 text-xs text-ink-faint">
                Backed by {analysis.evidence.length} evidence items · rules:{" "}
                {analysis.rules_triggered.join(", ") || "none"} · engine v
                {analysis.engine_version}
              </p>
            </div>
            <div>
              <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-ink-faint">
                Recommended next action
              </h3>
              <p>{analysis.recommended_actions[0] ?? "No action recommended."}</p>
            </div>
            {analysis.ai_explanation && (
              <div className="rounded border border-violet-500/30 bg-violet-500/5 p-3">
                <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-violet-300">
                  AI-generated explanation
                </h3>
                <p className="text-ink-dim">{analysis.ai_explanation}</p>
                <p className="mt-1.5 text-[11px] text-ink-faint">
                  Generated by an LLM from the deterministic analysis above; it
                  did not influence the diagnosis.
                </p>
              </div>
            )}
            {analysis.alternative_causes.length > 0 && (
              <div>
                <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-ink-faint">
                  Alternatives considered
                </h3>
                <ul className="space-y-1 text-xs text-ink-dim">
                  {analysis.alternative_causes.map((alt) => (
                    <li key={alt.category}>
                      {CATEGORY_LABELS[alt.category]}{" "}
                      <span className="tabular-nums">
                        ({Math.round(alt.score * 100)}%)
                      </span>{" "}
                      — {alt.reason}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
