"""GitHub issue generation from an incident + analysis (no OAuth required)."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote

from blackbox_api.analysis.features import event_t
from blackbox_api.reports.report import CATEGORY_LABELS
from blackbox_api.schemas import AnalysisResult, EventType, Incident, Severity

SEVERITY_LABELS = {
    Severity.INFO: "severity:info",
    Severity.WARNING: "severity:warning",
    Severity.ERROR: "severity:error",
    Severity.CRITICAL: "severity:critical",
}


def build_github_issue(
    incident: Incident, analysis: AnalysisResult | None, repo: str | None = None
) -> dict[str, Any]:
    category = analysis.failure_category.value if analysis else "unknown"
    label = CATEGORY_LABELS.get(category, category)
    title = (
        f"[{incident.robot_id}] {label}: {incident.task_name} "
        f"{incident.outcome.value.replace('_', ' ')}"
    )

    failure_events = [
        ev
        for ev in incident.events
        if ev.event_type
        in (EventType.TASK_TIMED_OUT, EventType.TASK_FAILED, EventType.ERROR_RAISED)
    ]

    lines: list[str] = []
    add = lines.append
    add("## Description")
    add("")
    add(incident.summary)
    if analysis:
        add("")
        add(
            f"BlackBox deterministic analysis attributes this to "
            f"**{label}** with **{analysis.confidence * 100:.0f}% confidence**."
        )
        add("")
        add(f"> {analysis.explanation}")
    add("")
    add("## Context")
    add("")
    add(f"- **Incident ID:** `{incident.id}`")
    add(f"- **Robot:** {incident.robot_id} ({incident.robot_model})")
    add(f"- **Facility:** {incident.facility} — {incident.environment}")
    add(f"- **Software version:** `{incident.software_version}`")
    add(f"- **Map version:** `{incident.map_version}`")
    add(f"- **Severity:** {incident.severity.value}")
    add(f"- **Outcome:** {incident.outcome.value}")
    add(
        f"- **Window:** {incident.start_time.isoformat()} → "
        f"{incident.end_time.isoformat()} ({incident.duration_s:.0f} s)"
    )
    add("")
    add("## Steps to reproduce")
    add("")
    add(f"1. Load facility map `{incident.map_version}`")
    add(
        f"2. Start robot {incident.robot_id} ({incident.robot_model}) on "
        f"software `{incident.software_version}`"
    )
    add(f"3. Issue task **{incident.task_name}** — {incident.task_goal}")
    add(
        f"4. Or replay deterministically in BlackBox: open incident "
        f"`{incident.id}` and press Play"
    )
    add("")
    add("## Expected behavior")
    add("")
    add(
        f"The robot completes task '{incident.task_name}' "
        f"({incident.task_goal}) without operator intervention."
    )
    add("")
    add("## Actual behavior")
    add("")
    if failure_events:
        for ev in failure_events:
            add(
                f"- `t={event_t(incident, ev):.1f}s` **{ev.event_type.value}** "
                f"({ev.subsystem.value}): {ev.message}"
            )
    else:
        add(f"- Task ended with outcome `{incident.outcome.value}`.")
    if analysis and analysis.evidence:
        add("")
        add("## Evidence")
        add("")
        for e in analysis.evidence:
            anchor = f"t={e.t:.1f}s"
            if e.t_end is not None:
                anchor += f"–{e.t_end:.1f}s"
            add(f"- **[{anchor}]** {e.summary}")
    if analysis and analysis.recommended_actions:
        add("")
        add("## Recommended investigation")
        add("")
        for i, action in enumerate(analysis.recommended_actions, 1):
            add(f"{i}. {action}")
    add("")
    add("---")
    add(
        f"_Generated by BlackBox from incident `{incident.id}` "
        f"(analysis engine {analysis.engine_version if analysis else 'n/a'})._"
    )
    body = "\n".join(lines)

    labels = ["blackbox", f"category:{category}", SEVERITY_LABELS[incident.severity]]
    issue_url = None
    if repo and "/" in repo:
        issue_url = (
            f"https://github.com/{repo}/issues/new?title={quote(title)}"
            f"&body={quote(body)}&labels={quote(','.join(labels))}"
        )
    return {
        "title": title,
        "body": body,
        "labels": labels,
        "markdown": f"# {title}\n\n{body}",
        "issue_url": issue_url,
    }
